[00:09:45] (server->proxy->client)::Error:{Une connexion existante a dû être fermée par l’hôte distant}::cause.toString(){java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant}
